universe = vanilla

executable = sample-analysis.sh
arguments = $(SampleID)
# alternate form, for both samples/lanes
# arguments = $(SampleID) $(Lane)

# transfer_input_files = /path/to/file1,/path/to/file2,etc
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# adjust these based on how much computing power 
# you need to analyze ONE set of paired end reads
request_cpus = 1
request_memory = 1GB
request_disk = 1GB

log = logs/$(Cluster).log
error = logs/$(Cluster)_$(SampleID).err
output = logs/$(Cluster)_$(SampleID).out

queue SampleID from samples.txt
# alternate form, for both samples/lanes
# queue SampleID,Lane from samples.txt
